### ISSUE TITLE
Full Screen opening in new tab for some experiments

### ISSUE THREAD

**Issue by madhavipuliraju** [vlabs-on-openedx/open-edx-micromachining-laboratory-coep#1]
Full Screen opening in new tab for the following experiments: 
1) To study pulsed-heating of materials 
2) Study of Electrochemical machining process 
3) Study the effect of process parameters in electrochemical grinding

**Comment by mrudhvika940** [comment]
Following change is made to the script. So full screen is now opening in new window

```
function popup(){
  window.open('url', '_blank', 'toolbar=0,location=0,menubar=0');
 }
```

**Comment by sravanthimodepu** [comment]
Closing the issue.
